apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-scripts"
data:
  download_data.py: |
    {{- .Values.dataScript | nindent 4 }}
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "mount/*" }}
  {{ $key := $path | trimPrefix "mount/" }}
  {{- $key }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
