site_name: SiloGen documentation
site_description: Documentation for SiloGen AMD Enterprise AI Platform
repo_url: https://github.com/silogen/docs
docs_dir: docs

theme:
  icon: material/developer-board
  logo: media/logo.svg
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - tags
  # - with-pdf

  - redirects:
      redirect_maps:
        'core/docs/developer-center/inference/index.md': 'core/docs/developer-center/inference/overview.md'
        'core/docs/developer-center/training/index.md': 'core/docs/developer-center/training/overview.md'
        'core/docs/airman/index.md': 'core/docs/airman/overview.md'
        'core/docs/airman/clusters/index.md': 'core/docs/airman/clusters/overview.md'
        'core/docs/airman/projects/index.md': 'core/docs/airman/projects/manage-projects.md'
        'core/docs/airman/users/index.md': 'core/docs/airman/users/overview.md'
        'platform-infrastructure/index.md': 'platform-infrastructure/on-premises-installation.md'
        'references/index.md': 'references/overview.md'

        # Change this to link to an external feedback page.
        # 'feedback.md': 'feedback-url.here'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: !relative $docs_dir
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true

nav:
  - Introduction:
    - Home: index.md
    - Platform overview: platform-overview.md
    - Target audience: target-audience.md
    - Quick start guide: quick-start.md
    - General topics:
      - Login to SiloGen: login-to-silogen.md
      - Personal preferences: personal-preferences.md

  - Infrastructure administrator:
    - Installation:
      - Supported environments: platform-infrastructure/supported-environments.md
      - On-premises installation: platform-infrastructure/on-premises-installation.md
      - DigitalOcean cloud installation: platform-infrastructure/digitalocean-installation.md

  - AI practitioner:
    - Developer Center overview: core/docs/developer-center/overview.md
    - Quick start guide: quick-start-guides/devcenter-quick-start.md
    - Workspaces: core/docs/developer-center/workspaces.md
    - Workloads: core/docs/developer-center/workloads.md

    - Training and fine-tuning:
      - Fine-tuning: core/docs/developer-center/training/fine-tuning.md
      - Models: core/docs/developer-center/training/models.md
      - Datasets: core/docs/developer-center/training/datasets.md

    - Inference:
      - Inference overview: core/docs/developer-center/inference/overview.md
      - Chat with models: core/docs/developer-center/inference/chat.md
      - Compare models: core/docs/developer-center/inference/compare.md

    - Tutorials:
      - GUI access:
        - No-code tutorial: tutorials/no-code-fine-tuning-tutorial.md
        - AI workspace tutorial: tutorials/ai-workspace-tutorial.md
        - Deploy a model and run inference: core/docs/developer-center/inference/how-to-deploy-and-inference.md
      - CLI access:
        - CLI tutorials overview: cli-tutorials-overview.md
        - Prerequisites for running the tutorials: ai-workloads-docs/tutorials/tutorial-prereqs.md
        - Deliver resources and fine-tune: ai-workloads-docs/tutorials/tutorial-01-deliver-resources-and-finetune.md
        - Language extension - Odia fine-tuning: ai-workloads-docs/tutorials/tutorial-02-language-extension-finetune.md

    - Reference AI workloads:
      - Workloads overview: ai-workloads-manifests/workloads-overview.md
      - dev-chatui-openwebui: ai-workloads-manifests/dev-chatui-openwebui/helm/README.md
      - dev-openvscode-server: ai-workloads-manifests/dev-workspace-vscode/helm/README.md
      - dev-text2image-comfyui: ai-workloads-manifests/dev-text2image-comfyui/helm/README.md
      - download-data-to-bucket: ai-workloads-manifests/download-data-to-bucket/helm/README.md
      - download-huggingface-model-to-bucket: ai-workloads-manifests/download-huggingface-model-to-bucket/helm/README.md
      - k8s-namespace-setup: ai-workloads-manifests/k8s-namespace-setup/helm/README.md
      - llm-finetune-silogen-engine:
        - LLM fine-tuning overview: ai-workloads-manifests/llm-finetune-silogen-engine/helm/README.md
        - Fine-tuning config: ai-workloads-manifests/llm-finetune-silogen-engine/helm/silogen_finetuning_config_readme.md
      - llm-inference-llamacpp-mi300x: ai-workloads-manifests/llm-inference-llamacpp-mi300x/helm/README.md
      - llm-inference-sglang: ai-workloads-manifests/llm-inference-sglang/helm/README.md
      - llm-inference-vllm: ai-workloads-manifests/llm-inference-vllm/helm/README.md
      - llm-inference-vllm-benchmark-mad: ai-workloads-manifests/llm-inference-vllm-benchmark-mad/helm/README.md

  - AI resource manager:
    - Airman overview: core/docs/airman/overview.md
    - Quick start guide: quick-start-guides/airman-quick-start.md
    - Dashboard: core/docs/airman/dashboard.md
    - Clusters:
      - Clusters overview: core/docs/airman/clusters/overview.md
      - Add new cluster: core/docs/airman/clusters/add-clusters-ui.md
    - Projects:
      - Projects overview: core/docs/airman/projects/manage-projects.md
      - Project dashboard: core/docs/airman/projects/project-dashboard.md
      - Project quotas: core/docs/airman/projects/project-quotas.md
    - User management:
      - Users overview: core/docs/airman/users/overview.md
      - Set up user management:
        - Enable single sign-on: core/docs/keycloak/sso.md
        - Configure SMTP and invite users: core/docs/keycloak/smtp-configuration.md
        - Add users manually: core/docs/keycloak/manual-user-management.md
      - Manage users: core/docs/airman/users/manage-users.md
    - Tutorials:
        - Resource utilization: tutorials/resource-utilization.md

  - References:
    - References: references/overview.md
    - Tags: references/tags.md

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  ref-architecture/SilogenAMDEnterpriseAIPlatform.md
  ref-architecture/Enterprise-AI-Architecture.md

  references/best-practices.md
  references/contributing.md

  # Imported files
  ai-workloads-docs/contributing.md
  ai-workloads-docs/getting-started.md
  ai-workloads-docs/tutorials.md
  ai-workloads-docs/workloads.md
  ai-workloads-manifests/dev-chatui-aiaio/helm/mount/README.md
  ai-workloads-manifests/dev-chatui-openwebui/helm/mount/README.md
  ai-workloads-manifests/dev-text2image-comfyui/helm/mount/README.md
  ai-workloads-manifests/dev-workspace-jupyterlab/helm/mount/README.md
  ai-workloads-manifests/dev-workspace-vscode/helm/mount/README.md
  ai-workloads-manifests/llm-inference-llamacpp-mi300x/helm/mount/README.md
  ai-workloads-manifests/llm-inference-ollama/helm/mount/README.md
  ai-workloads-manifests/llm-inference-openai-benchmark-guidellm/helm/mount/README.md
  ai-workloads-manifests/llm-inference-openai-benchmark-rocmblog/helm/mount/README.md
  ai-workloads-manifests/llm-inference-sglang/helm/mount/README.md
  ai-workloads-manifests/llm-inference-tgi/helm/mount/README.md
  ai-workloads-manifests/llm-inference-vllm-benchmark-mad/helm/mount/README.md
  ai-workloads-manifests/llm-inference-vllm-benchmark-rocmblog/helm/mount/README.md
  ai-workloads-manifests/llm-inference-vllm/helm/mount/README.md
  ai-workloads-manifests/llm-pretraining-megatron-lm/helm/mount/README.md
  ai-workloads-manifests/rag-embedding-infinity/helm/mount/README.md
