site_name: SiloGen documentation
site_description: Documentation for SiloGen AMD Enterprise AI Platform
repo_url: https://github.com/silogen/docs
docs_dir: docs
edit_uri: https://github.com/silogen/docs/blob/main

theme:
  icon: material/developer-board
  logo: media/logo.svg
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.action.edit
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest

plugins:
  - search
  - tags
 # - with-pdf
  - multirepo:
      cleanup: true
      nav_repos:
        - name: ai-workloads
          import_url: https://github.com/silogen/ai-workloads?branch=main
          imports: [docs/tutorials/*, workloads/workloads-overview.md, workloads/dev-chatui-openwebui/helm/README.md, workloads/dev-workspace-vscode/helm/README.md, workloads/dev-text2image-comfyui/helm/README.md, workloads/download-data-to-bucket/helm/README.md, workloads/download-huggingface-model-to-bucket/helm/README.md, workloads/k8s-namespace-setup/helm/README.md, workloads/llm-finetune-silogen-engine/helm/*,  workloads/llm-inference-llamacpp-mi300x/helm/README.md, workloads/llm-inference-sglang/helm/README.md, workloads/llm-inference-vllm/helm/README.md, workloads/llm-inference-vllm-benchmark-mad/helm/README.md]

        - name: core
          #import_url: https://github.com/silogen/core?branch=main
          import_url: git@github.com:silogen/core.git?branch=main
          imports: [docs/keycloak/sso.md, docs/silogen-docs/external-docs/docs/*]

        #- name: kaiwo
        #  import_url: https://github.com/silogen/kaiwo?branch=main
        #  imports: [docs/docs/*]

  - redirects:
      redirect_maps:
        'core/docs/silogen-docs/external-docs/docs/developer-center/inference/index.md': 'core/docs/silogen-docs/external-docs/docs/developer-center/inference/overview.md'
        'core/docs/silogen-docs/external-docs/docs/developer-center/training/index.md': 'core/docs/silogen-docs/external-docs/docs/developer-center/training/overview.md'
        'core/docs/silogen-docs/external-docs/docs/airman/index.md': 'core/docs/silogen-docs/external-docs/docs/airman/overview.md'
        'core/docs/silogen-docs/external-docs/docs/airman/clusters/index.md': 'core/docs/silogen-docs/external-docs/docs/airman/clusters/overview.md'
        'core/docs/silogen-docs/external-docs/docs/airman/quotas/index.md': 'core/docs/silogen-docs/external-docs/docs/airman/quotas/overview.md'
        'core/docs/silogen-docs/external-docs/docs/airman/users/index.md': 'core/docs/silogen-docs/external-docs/docs/airman/users/overview.md'
        'platform-infrastructure/index.md': 'platform-infrastructure/installation.md'
        'references/index.md': 'references/overview.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.snippets:
      base_path: !relative $docs_dir
  - admonition
  - footnotes
  - attr_list
  - toc:
      permalink: true

nav:
  - Introduction:
    - Home: index.md
    - Platform overview: platform-overview.md
    - Target audience: target-audience.md
    - General topics:
      - Login to SiloGen: login-to-silogen.md
      - Personal preferences: personal-preferences.md

  - Platform infrastructure:
    - Installation overview: platform-infrastructure/installation.md
    - Demo environment installation: platform-infrastructure/demo-environment.md
    - Enable single sign-on: core/docs/keycloak/sso.md

  - AI development:
    - Overview: core/docs/silogen-docs/external-docs/docs/developer-center/overview.md
    - AI catalog: core/docs/silogen-docs/external-docs/docs/developer-center/ai-catalog.md
    - Workloads: core/docs/silogen-docs/external-docs/docs/developer-center/workloads.md

    - Training and fine-tuning:
      - Overview: core/docs/silogen-docs/external-docs/docs/developer-center/training/overview.md
      - Models: core/docs/silogen-docs/external-docs/docs/developer-center/training/models.md
      - Datasets: core/docs/silogen-docs/external-docs/docs/developer-center/training/datasets.md
      - Fine-tuning: core/docs/silogen-docs/external-docs/docs/developer-center/training/fine-tuning.md

    - Inference:
      - Inference overview: core/docs/silogen-docs/external-docs/docs/developer-center/inference/overview.md
      - Chat: core/docs/silogen-docs/external-docs/docs/developer-center/inference/chat.md
      - Compare: core/docs/silogen-docs/external-docs/docs/developer-center/inference/compare.md

    - Tutorials:
      - Overview: ai-development-tutorials.md
      - Prerequisites for running the tutorials: ai-workloads/docs/tutorials/tutorial-prereqs.md
      - Deliver resources and fine-tune: ai-workloads/docs/tutorials/tutorial-01-deliver-resources-and-finetune.md
      - Language extension - Odia fine-tuning: ai-workloads/docs/tutorials/tutorial-02-language-extension-finetune.md

    - Reference AI workloads:
      - Overview: ai-workloads/workloads/workloads-overview.md
      - dev-chatui-openwebui: ai-workloads/workloads/dev-chatui-openwebui/helm/README.md
      - dev-openvscode-server: ai-workloads/workloads/dev-workspace-vscode/helm/README.md
      - dev-text2image-comfyui: ai-workloads/workloads/dev-text2image-comfyui/helm/README.md
      - download-data-to-bucket: ai-workloads/workloads/download-data-to-bucket/helm/README.md
      - download-huggingface-model-to-bucket: ai-workloads/workloads/download-huggingface-model-to-bucket/helm/README.md
      - k8s-namespace-setup: ai-workloads/workloads/k8s-namespace-setup/helm/README.md
      - llm-finetune-silogen-engine:
        - Overview: ai-workloads/workloads/llm-finetune-silogen-engine/helm/README.md
        - Fine-tuning config: ai-workloads/workloads/llm-finetune-silogen-engine/helm/silogen_finetuning_config_readme.md
      - llm-inference-llamacpp-mi300x: ai-workloads/workloads/llm-inference-llamacpp-mi300x/helm/README.md
      - llm-inference-sglang: ai-workloads/workloads/llm-inference-sglang/helm/README.md
      - llm-inference-vllm: ai-workloads/workloads/llm-inference-vllm/helm/README.md
      - llm-inference-vllm-benchmark-mad: ai-workloads/workloads/llm-inference-vllm-benchmark-mad/helm/README.md

  - AI resource management:
    - Overview: core/docs/silogen-docs/external-docs/docs/airman/overview.md
    - Dashboard: core/docs/silogen-docs/external-docs/docs/airman/dashboard.md
    - Clusters:
      - Clusters overview: core/docs/silogen-docs/external-docs/docs/airman/clusters/overview.md
      - Add new cluster: core/docs/silogen-docs/external-docs/docs/airman/clusters/add-clusters-ui.md
    - Quotas:
      - Quotas overview: core/docs/silogen-docs/external-docs/docs/airman/quotas/overview.md
      - Set quotas: core/docs/silogen-docs/external-docs/docs/airman/quotas/set-quotas.md
    - User management:
      - Users overview: core/docs/silogen-docs/external-docs/docs/airman/users/overview.md
      - Manage users: core/docs/silogen-docs/external-docs/docs/airman/users/manage-users.md
      - Manage user groups: core/docs/silogen-docs/external-docs/docs/airman/users/manage-user-groups.md

  - References:
    - Overview: references/overview.md
    - Tags: references/tags.md

extra_css:
  - stylesheets/extra.css

exclude_docs: |
  ref-architecture/SilogenAMDEnterpriseAIPlatform.md
  ref-architecture/Enterprise-AI-Architecture.md

  references/best-practices.md
  references/contributing.md