metadata:
  labels: {}
  project_id: silogen
  user_id: user
  workload_id: # defaults to the release name

image: rocm/pytorch:rocm6.4_ubuntu24.04_py3.12_pytorch_release_2.6.0
imagePullPolicy: Always
gpus: 1
memory_per_gpu: 128 # Gi
cpu_per_gpu: 4

env_vars:
  BUCKET_STORAGE_HOST: http://minio.minio-tenant-default.svc.cluster.local:80
  BUCKET_STORAGE_ACCESS_KEY:
    name: minio-credentials
    key: minio-access-key
  BUCKET_STORAGE_SECRET_KEY:
    name: minio-credentials
    key: minio-secret-key

storage:
  ephemeral:
    quantity: 128Gi
    storageClassName: mlstorage
    accessModes:
      - ReadWriteOnce
  dshm:
    sizeLimit: 16Gi

deployment:
  ports:
    http: 8080

# startupProbe - checks if the container has successfully started. It disables liveness and readiness probes until it succeeds, useful for slow-starting applications.
# livenessProbe - checks if the container is still alive. If it fails, Kubernetes restarts the container to recover from failure.
# readinessProbe - checks if the container is ready to serve traffic. If it fails, the container is removed from the service's endpoints but remains running.
# ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
startupProbe:
  httpGet:
    path: /healthz
    port: http
  failureThreshold: 20
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /healthz
    port: http

entrypoint: |
  curl -fsSL https://code-server.dev/install.sh | sh
  mkdir -p /root/.local/share/code-server/User/
  cp /workload/mount/default_settings.json /root/.local/share/code-server/User/settings.json
  code-server --install-extension ms-python.python
  code-server --install-extension GitHub.vscode-pull-request-github
  code-server --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
  code-server --auth none --bind-addr 0.0.0.0:8080

# kaiwo settings (if enabled, use kaiwo CRDs to have kaiwo operator manage the workload)
kaiwo:
  enabled: false

http_route:
  enabled: false

ingress:
  enabled: false

persistent_storage:
  enabled: false
  volumes:
    pvc-user:
      pvc_name: "pvc-user-{{ .Values.metadata.user_id }}"
      mount_path: "/workload/{{ .Values.metadata.user_id }}"
