# Which model to download
modelID: meta-llama/Llama-3.1-70B

# Where the resources should be stored:
bucketPath: default-bucket/models/meta-llama/Llama-3.1-70B
bucketStorageHost: http://minio.minio-tenant-default.svc.cluster.local:80

# Download & Upload configuration:
downloadExcludeGlob: "original/*"  # Exclude things from the HuggingFace download with this
allowOverwrite: false

# Storage configuration:
storageClass: mlstorage
storageQuantity: "20Gi"

# HF Token:
hfTokenSecret:
  name: hf-token
  key: hf-token
