#!/bin/sh
# end this script as soon as any command fails
set -e

# Check if this is a tag-only push by examining the arguments passed to pre-push
# shellcheck disable=SC2034  # These variables are provided by Git but we only use local_ref
while read -r local_ref local_sha remote_ref remote_sha
do
    # Skip if pushing tags
    if [[ $local_ref == refs/tags/* ]]; then
        exit 0
    fi
done

# Run only if there are changes in the docs/silogen-docs directory (committed or staged/unstaged)
if { git diff --name-only HEAD^ HEAD; git status -uno --porcelain; } | grep --quiet "docs/silogen-docs"; then

    # Change to docs/silogen-docs from any path
    git_root=$(git rev-parse --show-toplevel)
    cd "$git_root/docs/silogen-docs" || exit

    echo "Running Prettier..."
    npm run format

    echo "Running ESLint..."
    npm run lint

    echo "Building the project"
    npm run build

    echo "Running tests"
    npm run test

fi
