external_secret:
  setup: true
  external_secret_name: "minio-credentials-fetcher"
  src:
    secret_store_name: "k8s-secret-store"
    remote_secret_name: "default-user"
    access_key_name: "API_ACCESS_KEY"
    secret_key_name: "API_SECRET_KEY"
  dest:
    k8s_secret_name: "minio-credentials"
    access_key_name: "minio-access-key"
    secret_key_name: "minio-secret-key"
