### General chart values ###
image: ghcr.io/silogen/logistics:v0.1

# Use to add labels to the metadata of the resources created by this workload.
labels: {}
  # Example:
  # labels:
  #   kaiwo.silogen.ai/managed: "true"

# Extra annotations such as an imagePullSecrets
imagePullSecrets: []
  # Example:
  # imagePullSecrets:
  #   - "regcred"

# Configure these to match the credentials in your cluster:
bucketStorageHost: http://minio.minio-tenant-default.svc.cluster.local:80
bucketCredentialsSecret:
  name: minio-credentials
  accessKeyKey: minio-access-key
  secretKeyKey: minio-secret-key
hfTokenSecret: {} # Optional secret reference that contains the Huggingface token
# Example:
# hfTokenSecret:
#   name: hf-token
#   key: hf-token

# Inputs:
modelID: "yujiepan/llama-3.1-tiny-random" # Huggingface model id, which is in the format of organization/model-name
bucketPath: default-bucket/models/yujiepan/llama-3.1-tiny-random # Path in the bucket storage where this model should be stored. In the format bucket-name/path/separated/by/slashes/name-for-resulting-directory
modelRevision: # Optional string that specifies which revision of the model should be downloaded.
downloadExcludeGlob: "original/*" # Optional string that specifies which files in the huggingface model repository should be excluded from the download
allowOverwrite: false # Optionally set to true to allow overiwriting existing files in the bucket
storageQuantity: 64Gi  # How much space needs to be allocated to store the model in the container (before pushing to bucket storage).
storageClass: mlstorage # Set this to use a specific storageClass for the storage. If not specified, will simply use an ephemeral_storage request.
