apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configs"
data:
{{- $files := .Files }}
{{- range $path, $_ := .Files.Glob "mount/*" }}
  {{ $key := $path | trimPrefix "mount/" }}
  {{- $key }}: |
{{ $files.Get $path | indent 4 }}
{{- end }}
