# image/model
model: "neuralmagic/Mistral-7B-Instruct-v0.3-FP8"
gpus: 2
vllm_engine_args:
  gpu_memory_utilization: "0.9"
  num-scheduler-steps: "10"
  max-num-seqs: "1024"
  dtype: "float16"
  quantization: "fp8"
  kv-cache-dtype: "fp8"
