name: Merge changes from a temporary branch in Docs Repo to main
# This workflow is triggered when there is a push to the "core-docs-updated" branch in the docs repository. "core-docs-updated" branch is created by a another workflow in the core repo to sync documentation updates between core and docs repos

on:
  push:
    branches:
      - core-docs-updated
      #- copy-files-to-docs-testing
    paths:
      - "docs/silogen-docs/external-docs/docs/**"
      - ".github/workflows/copy-docs-files-to-docs-repo.yml"

jobs:
  copy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout core repo
        uses: actions/checkout@v4

      - name: Merge documentation changes from branch to main
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/silogen/docs.git silogen_docs
          BRANCH_NAME="core-docs-updated"
          cd silogen_docs
          git checkout main
          git merge core-docs-updated
          git diff --staged --quiet || git commit -m "Merge changes from core-docs-updated branch into main"
          git push origin $BRANCH_NAME
        env:
          DOCS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}