name: Merge a hotfix branch to main

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'docs/stylesheets/**'

jobs:
  echo:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'hotfix/') # Check if merged a hotfix branch

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0 # Fetch all history for accurate diffing

    - name: Print a message
      run: |
        echo "A hotfix was merged into main with changes in stylesheets directory"

        # You can then iterate through $changedFiles and perform actions on each file
        changedFiles=$(git diff --name-only HEAD^)
        echo "Changed files: $changedFiles"

        # Make a diff variable
        diffContent=$(git diff HEAD^)
        echo "Diff Content:"
        echo "$diffContent"
        git diff HEAD^ > pr.patch

        cat pr.patch

        # Clone the target repository
        #git config --global user.name 'GitHub Actions'
        #git config --global user.email 'actions@github.com'
        #git clone https://x-access-token:${{ secrets.DOCS_REPO_TOKEN }}@github.com/silogen/AMDEnterpriseAISuiteDocs.git target_docs
        #cd target_docs

        #git checkout -b hotfix-merge-temp

      env:
        DOCS_REPO_TOKEN: ${{ secrets.DOCS_REPO_TOKEN }}
